// <auto-generated />
using System;
using IFRS16_Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IFRS16_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251121162043_AddExistingStoredProcedures")]
    partial class AddExistingStoredProcedures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IFRS16_Backend.Models.AllLeasesReportTable", b =>
                {
                    b.Property<double?>("AdditionsDuringYearLL")
                        .HasColumnType("float");

                    b.Property<double?>("AdditionsDuringYearROU")
                        .HasColumnType("float");

                    b.Property<double?>("Amortization")
                        .HasColumnType("float");

                    b.Property<double?>("ClosingLL")
                        .HasColumnType("float");

                    b.Property<double?>("ClosingROU")
                        .HasColumnType("float");

                    b.Property<DateTime>("CommencementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CurrencyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Exchange_Gain_Loss")
                        .HasColumnType("float");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Interest")
                        .HasColumnType("float");

                    b.Property<int>("LeaseId")
                        .HasColumnType("int");

                    b.Property<string>("LeaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ModificationAdjustmentLL")
                        .HasColumnType("float");

                    b.Property<double?>("ModificationAdjustmentROU")
                        .HasColumnType("float");

                    b.Property<double?>("OpeningLL")
                        .HasColumnType("float");

                    b.Property<double?>("OpeningROU")
                        .HasColumnType("float");

                    b.Property<double?>("Payment")
                        .HasColumnType("float");

                    b.Property<double>("Rental")
                        .HasColumnType("float");

                    b.ToTable("AllLeasesReport");
                });

            modelBuilder.Entity("IFRS16_Backend.Models.CurrenciesTable", b =>
                {
                    b.Property<int>("CurrencyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurrencyID"));

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrencyID");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("IFRS16_Backend.Models.DisclouserMaturityAnalysisTable", b =>
                {
                    b.Property<decimal?>("AfterFiveYears")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BetweenOneAndFiveYears")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LessThanOneYear")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("DisclouserMaturityAnalysis");
                });

            modelBuilder.Entity("IFRS16_Backend.Models.ExchangeRateTable", b =>
                {
                    b.Property<int>("ExchangeRateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExchangeRateID"));

                    b.Property<int>("CurrencyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExchangeDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ExchangeRateID");

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("IFRS16_Backend.Models.ExtendedLeaseDataSP", b =>
                {
                    b.Property<int>("LeaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaseId"));

                    b.Property<string>("Annuity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommencementDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrencyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("GRV")
                        .HasColumnType("float");

                    b.Property<double>("IBR")
                        .HasColumnType("float");

                    b.Property<double?>("IDC")
                        .HasColumnType("float");

                    b.Property<double?>("Increment")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rental")
                        .HasColumnType("float");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeaseId");

                    b.ToTable("LeaseDataSP");
                });

            modelBuilder.Entity("IFRS16_Backend.Models.FC_JournalEntryTable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("JE_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeaseId")
                        .HasColumnType("int");

                    b.Property<string>("Particular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("FC_JournalEntries");
                });

            modelBuilder.Entity("IFRS16_Backend.Models.FC_LeaseLiabilityTable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("Closing")
                        .HasColumnType("float");

                    b.Property<double>("Interest")
                        .HasColumnType("float");

                    b.Property<int>("LeaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LeaseLiability_Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Opening")
                        .HasColumnType("float");

                    b.Property<double>("Payment")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("FC_LeaseLiability");
                });

            modelBuilder.Entity("IFRS16_Backend.Models.FC_ROUScheduleTable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("Amortization")
                        .HasColumnType("float");

                    b.Property<double>("Closing")
                        .HasColumnType("float");

                    b.Property<int>("LeaseId")
                        .HasColumnType("int");

                    b.Property<double>("Opening")
                        .HasColumnType("float");

                    b.Property<DateTime>("ROU_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("FC_ROUSchedule");
                });

            modelBuilder.Entity("IFRS16_Backend.Models.InitialRecognitionTable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LeaseId")
                        .HasColumnType("int");

                    b.Property<decimal>("NPV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rental")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SerialNo")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("InitialRecognition");
                });

            modelBuilder.Entity("IFRS16_Backend.Models.JournalEntryReport", b =>
                {
                    b.Property<decimal?>("Credit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Debit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Particular")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("JournalEntryReport");
                });

            modelBuilder.Entity("IFRS16_Backend.Models.JournalEntryTable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("JE_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeaseId")
                        .HasColumnType("int");

                    b.Property<string>("Particular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("IFRS16_Backend.Models.LeaseContract", b =>
                {
                    b.Property<int>("LeaseContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaseContractId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ContractDoc")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeaseId")
                        .HasColumnType("int");

                    b.HasKey("LeaseContractId");

                    b.ToTable("LeaseDataContracts");
                });

            modelBuilder.Entity("IFRS16_Backend.Models.LeaseFormData", b =>
                {
                    b.Property<int>("LeaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaseId"));

                    b.Property<string>("Annuity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommencementDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("GRV")
                        .HasColumnType("float");

                    b.Property<double>("IBR")
                        .HasColumnType("float");

                    b.Property<double?>("IDC")
                        .HasColumnType("float");

                    b.Property<double?>("Increment")
                        .HasColumnType("float");

                    b.Property<string>("IncrementalFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rental")
                        .HasColumnType("float");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeaseId");

                    b.ToTable("LeaseData");
                });

            modelBuilder.Entity("IFRS16_Backend.Models.LeaseLiabilityTable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("Closing")
                        .HasColumnType("float");

                    b.Property<double?>("Exchange_Gain_Loss")
                        .HasColumnType("float");

                    b.Property<double>("Interest")
                        .HasColumnType("float");

                    b.Property<int>("LeaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LeaseLiability_Date")
                        .HasColumnType("datetime2");

                    b.Property<double?>("ModificationAdjustment")
                        .HasColumnType("float");

                    b.Property<double>("Opening")
                        .HasColumnType("float");

                    b.Property<double>("Payment")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("LeaseLiability");
                });

            modelBuilder.Entity("IFRS16_Backend.Models.LeaseReportSummaryTable", b =>
                {
                    b.Property<double?>("Amortization")
                        .HasColumnType("float");

                    b.Property<double?>("ClosingLL")
                        .HasColumnType("float");

                    b.Property<double?>("ClosingROU")
                        .HasColumnType("float");

                    b.Property<double?>("Exchange_Gain_Loss")
                        .HasColumnType("float");

                    b.Property<double?>("Interest")
                        .HasColumnType("float");

                    b.Property<double?>("OpeningLL")
                        .HasColumnType("float");

                    b.Property<double?>("OpeningROU")
                        .HasColumnType("float");

                    b.Property<double?>("Payment")
                        .HasColumnType("float");

                    b.ToTable("LeasesReportSummary");
                });

            modelBuilder.Entity("IFRS16_Backend.Models.ROUScheduleTable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("Amortization")
                        .HasColumnType("float");

                    b.Property<double>("Closing")
                        .HasColumnType("float");

                    b.Property<int>("LeaseId")
                        .HasColumnType("int");

                    b.Property<double?>("ModificationAdjustment")
                        .HasColumnType("float");

                    b.Property<double>("Opening")
                        .HasColumnType("float");

                    b.Property<DateTime>("ROU_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("ROUSchedule");
                });

            modelBuilder.Entity("IFRS16_Backend.Models.SessionTokenTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SessionToken");
                });
#pragma warning restore 612, 618
        }
    }
}
